### ISSUE TITLE
ImportError: No module named ast

### ISSUE THREAD

**Issue by bestycame** [cocazoulou/couchpotato.provider.t411#5]
Bonjour,
Je recois l'erreur suivante lors de l'ajout du plugin sur une installation de CP 3.0.1 Win32.

```
11-15 11:19:43
DEBUG
[  couchpotato.core.loader] Skip loading module plugin t411: Traceback (most recent call last):
  File "C:\Users\****\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\loader.py", line 164, in loadModule
  File "C:\Users\****\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\libs\importhelper\__init__.py", line 37, in import_module
  File "C:\Users\****\AppData\Roaming\CouchPotato\custom_plugins\t411\__init__.py", line 1, in <module>
  File "C:\Users\****\AppData\Roaming\CouchPotato\custom_plugins\t411\main.py", line 16, in <module>
ImportError: No module named ast
```

Bien à vous,

**Comment by bestycame** [comment]
PEBCAK (Problem Exists Between Chair And Keyboard)
Sorry for that!
